use_frameworks!

target 'Algent_Example' do
  pod 'Algent', :path => '../'

  target 'Algent_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2'
  pod 'Nimble', '~> 7.3'
  pod 'FBSnapshotTestCase' , '~> 2.1'
  pod 'Nimble-Snapshots' , '~> 6.3'
  end
end
